Repository kakao-tech-campus-2nd-step2/android-map-keyword, pull requests merged in 2024-07, with the labels that each got.

#1 부산대 Android_노신 2주차 과제 (1단계)
  README.md
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/java/campus/tech/kakao/map/SQLiteDb.kt
  app/src/main/java/campus/tech/kakao/map/SQLiteHelper.kt
  app/src/main/res/layout/activity_main.xml
Labels: step2 Android 이오형 멘토, step1

#2 부산대 Android_김현민_2주차_과제_Step1
  README.md
  app/src/main/java/campus/tech/kakao/map/DBHelper.kt
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/res/drawable/close.png
  app/src/main/res/layout/activity_main.xml
Labels: step2 Android 이오형 멘토, step1

#8 부산대 Android_김정희_2주차 과제_1단계
  README.md
  app/src/main/java/campus/tech/kakao/map/DbHelper.kt
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/java/campus/tech/kakao/map/MapContract.kt
  app/src/main/java/campus/tech/kakao/map/MapViewModel.kt
  app/src/main/res/drawable/close_24px.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: step2 Android 이오형 멘토, step1

#13 [부산대 Android_김주송] 2주차 과제 STEP1
  README.md
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/java/campus/tech/kakao/map/PlaceContract.kt
  app/src/main/java/campus/tech/kakao/map/PlaceDatabaseAccess.kt
  app/src/main/java/campus/tech/kakao/map/PlaceDatabaseHelper.kt
  app/src/main/res/drawable/close.png
  app/src/main/res/layout/activity_main.xml
Labels: step2 Android 이오형 멘토, step1

#62 부산대Android_박정훈_2주차_과제_Step2
  README.md
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/campus/tech/kakao/map/DiffUtilCalback.kt
  app/src/main/java/campus/tech/kakao/map/LocationContract.kt
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/java/campus/tech/kakao/map/model/Location.kt
  app/src/main/java/campus/tech/kakao/map/model/Repository.kt
  app/src/main/java/campus/tech/kakao/map/view/ViewActivity.kt
  app/src/main/java/campus/tech/kakao/map/view/adapter/LocationAdapter.kt
  app/src/main/java/campus/tech/kakao/map/view/adapter/LogAdapter.kt
  app/src/main/java/campus/tech/kakao/map/viewmodel/LocationViewModel.kt
  app/src/main/java/campus/tech/kakao/map/viewmodel/LocationViewModelFactory.kt
  app/src/main/res/drawable/icon_cancel.xml
  app/src/main/res/drawable/icon_location.png
  app/src/main/res/drawable/icon_x.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/layout/log_item.xml
Labels: step2 Android 이오형 멘토, step2

#42 부산대 Android_김현민 2주차 과제 Step2
  README.md
  app/build.gradle.kts
  app/src/main/java/campus/tech/kakao/map/Adapter.kt
  app/src/main/java/campus/tech/kakao/map/DBHelper.kt
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/java/campus/tech/kakao/map/Profile.kt
  app/src/main/res/drawable/location.png
  app/src/main/res/layout/activity_item_view.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/search_save.xml
Labels: step2 Android 이오형 멘토

#60 부산대 Android_이지은 2주차 2단계 제출(수정)
  README.md
  app/build.gradle.kts
  app/src/main/java/campus/tech/kakao/map/Contract.kt
  app/src/main/java/campus/tech/kakao/map/Location.kt
  app/src/main/java/campus/tech/kakao/map/LocationAdapter.kt
  app/src/main/java/campus/tech/kakao/map/LocationDbAccessor.kt
  app/src/main/java/campus/tech/kakao/map/LocationDbHelper.kt
  app/src/main/java/campus/tech/kakao/map/LocationViewModel.kt
  app/src/main/java/campus/tech/kakao/map/MainActivity.kt
  app/src/main/java/campus/tech/kakao/map/SavedLocation.kt
  app/src/main/java/campus/tech/kakao/map/SavedLocationAdapter.kt
  app/src/main/java/campus/tech/kakao/map/SavedLocationViewModel.kt
  app/src/main/java/campus/tech/kakao/map/ViewModelFactory.kt
  app/src/main/java/campus/tech/kakao/map/onItemSelected.kt
  app/src/main/res/drawable/location_icon.png
  app/src/main/res/drawable/x_mark.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_location.xml
  app/src/main/res/layout/item_saved_location.xml
Labels: step2 Android 강대규 멘토
